---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/adtennis/public_html/project-holders-project-2
    - find . \( -type f -a ! -name 'manifest.json' -a ! -name 'db_conn.php' -a ! -path './Images/membership-payment-proof/*' -a ! -path './Images/news/*' -a ! -path './Images/payment-proof/*' -a ! -path './Images/profile-pic/*' \) -exec cp -r {} $DEPLOYPATH/ \;

    


