---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/adtennis/public_html/project-holders-project-2
    - find . -type f -not -name 'db_conn.php' -exec cp -r {} $DEPLOYPATH/{} \;
    - cp -r /path/to/db_conn.php $DEPLOYPATH


    


