---
deployment: 
  tasks:
    - export DEPLOYPATH=/home2/adtennis/public_html/project-holders-project-2
    - /bin/cp -r * $DEPLOYPATH

  excludes:
    - manifest.json
    - db_conn.php
    - Images/membership-payment-proof
    - Images/news
    - Images/payment-proof
    - Images/profile-pic
    


