---
deployment:
  tasks:
    - export DEPLOYPATH=/home/adtennis/public_html/
    - /bin/cp * $DEPLOYPATH

   excludes:
    - project-holders-project-2/db_conn.php
    - project-holders-project-2/manifest.json


    