---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/adtennis/public_html/project-holders-project-2
    - find . -type d -exec mkdir -p $DEPLOYPATH/{} \;
    - find . -type f -exec sh -c '
          for file do
              case "$file" in
                  */manifest.json|*/db_conn.php|*/Images/membership-payment-proof/*|*/Images/news/*|*/Images/payment-proof/*|*/Images/profile-pic/*) ;;
                  *) cp -r "$file" "$DEPLOYPATH/$file" ;;
              esac
          done
      ' sh {} +


    


