---
deployment:
  tasks:
    - export DEPLOYPATH=/home2/adtennis/public_html/project-holders-project-2
    - find . -type f -not -name 'db_conn.php' -not -name 'manifest.json' -not -path './Images/membership-payment-proof/*' -exec cp -r {} $DEPLOYPATH/{} \;
    


    


